### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by eliaslevy**
Rebased and regenerated the Windows bindings with the new version of `bindgen`.

Requires building Hyperscan from source and then pointing HYPERSCAN_ROOT to the Hyperscan build or install directory.  Hyperscan must be build with the Release config using the `--config Release` argument to `cmake` or by executing `MSBuild.exe ALL_BUILD.vcxproj -p:Configuration=Release`.  Using `CMAKE_BUILD_TYPE` to select the build type won't work in Windows.

I added `doctest=false` to the `hyperscan-sys` crate as the doc comments generated by `bindgen` were tripping up `cargo test`.

### CODE REVIEW

**Comment by eliaslevy** [comment]
Would it be possible to merge this PR?

**Comment by flier** [comment]
> Would it be possible to merge this PR?

sorry, it was my mistake that missed this PR

**Comment by eliaslevy** [comment]
No worries.  Thank you for merging it.

**Comment by eliaslevy** [comment]
@flier could we bump the release version?

**Pull request merged**
